### ISSUE TITLE
Add support for ClientCertificateId

### ISSUE THREAD

**Issue by icj217** [leftclickben/serverless-api-stage#4]
It would be nice to be able to specify a ClientCertificateId value since this is a stage setting. It seems like it would just require an additional line to be added here:
https://github.com/leftclickben/serverless-api-stage/blob/bce93e6a67bcddee1e7b4500a2aca7d6c01ece68/src/index.js#L114
along the lines of:
`ClientCertificateId: stageSettings.ClientCertificateId || {},`

Thoughts? Is this possible?

**Comment by leftclickben** [comment]
@icj217 Sorry for delay getting back on this, I think that should be possible, I'll take a look

**Comment by leftclickben** [comment]
@icj217 Are you able to test using #7?  I haven't got anything set up to use client certs to test with.
